config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


api_patterns = [
    url(r'^', include('fighters.api.urls')),
    url(r'^', include('events.api.urls')),
]


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(api_patterns, namespace='api')),
    url(r'subscription/', include('subscriptions.urls')),
    url(r'', include('fighters.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns

ufcroster/events/api/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'events', views.EventViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
]

ufcroster/fighters/urls.py
from django.conf.urls import url

from . import views

app_name = 'fighters'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<country_code>[\w]{2})/$', views.UpcomingFightsByCountry.as_view(), name='upcoming_by_country'),
    url(r'^(?P<country_code>[\w]{2})/fighters$', views.FightersByCountry.as_view(), name='by_country'),
    url(r'^fighter/(?P<slug>[\w\-]+)/$', views.FighterDetail.as_view(), name='detail'),
]

ufcroster/subscriptions/urls.py
from django.conf.urls import url

from . import views

app_name = 'subscriptions'


urlpatterns = [
    url(r'^$', views.Subscribe.as_view(), name='subscribe'),
    url(r'^activate$', views.ActivateSubscription.as_view(), name='activate'),
    url(r'^deactivate$', views.DeactivateSubscription.as_view(), name='deactivate'),
]

ufcroster/common/models.py
from django.db import models


class TimeStampedModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

ufcroster/events/models.py
from django.db import models

from common.models import TimeStampedModel


class Event(TimeStampedModel):
    title = models.CharField(max_length=255)
    date = models.DateTimeField(blank=True, null=True)
    location = models.CharField(max_length=255, blank=True)
    venue = models.CharField(max_length=255, blank=True)
    poster = models.ImageField(blank=True)
    promotion = models.CharField(max_length=255, blank=True)
    sherdog_url = models.URLField(max_length=255, blank=True, null=True)
    ufc_url = models.URLField(max_length=255, blank=True, null=True)
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.title

ufcroster/subscriptions/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from model_utils.models import TimeStampedModel

from .managers import NotificationManager, SubscriptionsManager


class Notification(TimeStampedModel):
    UPCOMING = 'U'
    RESULTS = 'R'

    TYPES = (
        (UPCOMING, 'Upcoming'),
        (RESULTS, 'Results')
    )

    type = models.CharField(max_length=4, choices=TYPES)
    response_id = models.CharField(max_length=128, blank=True, null=True)

    objects = NotificationManager()


class Subscription(TimeStampedModel):
    email = models.EmailField(unique=True)
    token = models.CharField(max_length=256, unique=True)
    is_active = models.BooleanField(default=False)

    objects = SubscriptionsManager()

    def __str__(self):
        return f'{self.email} Active: {self.is_active}'

    @property
    def action_link(self):
        if self.token:
            if not self.is_active:
                part_url = reverse('subscriptions:activate')
                return f'{settings.SITE_URL}{part_url}?token={self.token}'
            else:
                part_url = reverse('subscriptions:deactivate')
                return f'{settings.SITE_URL}{part_url}?token={self.token}'

    @property
    def unsubscribe_dict(self):
        return {'unsubscribe': self.action_link}

ufcroster/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

ufcroster/subscriptions/forms.py
from django.forms import ModelForm, ValidationError

from .models import Subscription


class SubscriptionForm(ModelForm):
    class Meta:
        model = Subscription
        fields = ('email', )

    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            subscription = Subscription.objects.get(email=email)
        except Subscription.DoesNotExist:
            return email
        else:
            if subscription.is_active:
                raise ValidationError('You have already subscribed.')
            if not subscription.is_active and subscription.token:
                raise ValidationError('Activation link already sent.')
            raise ValidationError('Please contact admin@ufcroster.com')

ufcroster/events/api/views.py
from rest_framework import viewsets

from .serializers import EventSerializer
from ..models import Event


class EventViewSet(viewsets.ModelViewSet):
    queryset = Event.objects.all()
    serializer_class = EventSerializer
    lookup_field = 'id'

ufcroster/fighters/api/views.py
from django.shortcuts import get_object_or_404
from rest_framework import viewsets

from .serializers import FighterSerializer, FightSerializer
from ..models import Fighter, Fight


class FighterViewSet(viewsets.ModelViewSet):
    queryset = Fighter.objects.details()
    serializer_class = FighterSerializer
    lookup_field = 'slug'


class FightViewSet(viewsets.ModelViewSet):
    serializer_class = FightSerializer

    def get_serializer(self, *args, **kwargs):
        if 'data' in kwargs:
            data = kwargs['data']
            if isinstance(data, list):
                kwargs['many'] = True

        return super().get_serializer(*args, **kwargs)

    def get_queryset(self):
        slug = self.kwargs.get('slug')
        fighter = get_object_or_404(Fighter, slug=slug)
        return Fight.objects.full_fights(fighter=fighter)

ufcroster/fighters/views.py
from django.conf import settings
from django.http import Http404
from django.views.generic import DetailView, ListView, TemplateView

from .models import Fighter, Fight


class CountryCodeMixin:
    def get_country_code(self):
        country_code = self.kwargs.get('country_code', '').upper()
        if country_code in settings.COUNTRIES_URL_CODES:
            return country_code
        raise Http404


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        fights_qs = Fight.objects.upcoming().fight_with_relations()
        context['closest_fights'] = fights_qs.order_by('details__date')[:5]
        context['recently_added_fights'] = fights_qs.order_by('-created')[:5]
        context['recently_created_fighters'] = Fighter.objects.details().active().order_by('-created')[:5]
        return context


class FighterDetail(DetailView):
    model = Fighter
    queryset = Fighter.objects.details()
    context_object_name = 'fighter'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['fights_list'] = Fight.objects.fight_with_relations().filter(fighter=self.object)
        return context


class UpcomingFightsByCountry(CountryCodeMixin, ListView):
    context_object_name = 'fights'
    template_name = 'fighters/upcoming_by_country.html'

    def get_queryset(self):
        return Fight.objects.upcoming_by_country(self.get_country_code()).order_by('details__date')


class FightersByCountry(CountryCodeMixin, ListView):
    context_object_name = 'fighters'
    template_name = 'fighters/fighters.html'

    def get_queryset(self):
        in_ufc = 'released_retired' not in self.request.GET.keys()
        return Fighter.objects.by_country(self.get_country_code()).filter(in_ufc=in_ufc)

ufcroster/subscriptions/views.py
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import redirect
from django.views.generic import View
from django.views.generic.edit import BaseCreateView

from .forms import SubscriptionForm
from .models import Subscription
from .utils import generate_token


class Subscribe(BaseCreateView):
    model = Subscription
    form_class = SubscriptionForm
    http_method_names = ['post']

    def form_invalid(self, form):
        return JsonResponse({'msg': form.errors.get('email', 'Something went wrong.')})

    def form_valid(self, form):
        form.save()
        return JsonResponse({'msg': 'Thank you for subscribing. Email has been sent to you with activation link.'})


class ActivateSubscription(View):
    def get(self, request, *args, **kwargs):
        token = request.GET.get('token')
        if token:
            try:
                subscription = Subscription.objects.get(token=token, is_active=False)
            except Subscription.DoesNotExist:
                messages.error(request, 'Activation link is no longer valid.')
            else:
                subscription.is_active = True
                subscription.token = generate_token(subscription.email, True)  # generating deactivation token
                subscription.save()
                messages.success(request, 'Subscription has been activated.')
        else:
            messages.error(request, 'Token not provided.')

        return redirect('fighters:index')


class DeactivateSubscription(View):
    def get(self, request, *args, **kwargs):
        token = request.GET.get('token')
        if token:
            try:
                subscription = Subscription.objects.get(token=token, is_active=True)
            except Subscription.DoesNotExist:
                messages.error(request, 'Deactivation link is no longer valid.')
            else:
                subscription.delete()
                messages.success(request, 'Subscription has been deactivated.')
        else:
            messages.error(request, 'Token not provided.')

        return redirect('fighters:index')

ufcroster/templates/base.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
<head>
  <title>
    UFC Roster!
    {% block title %}
    {% endblock %}
  </title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="https://maxcdn.bootstrapcdn.com/bootswatch/4.0.0/flatly/bootstrap.min.css" rel="stylesheet" integrity="sha384-jb1k1ntK2AaXuVTIiFXgcGvjcWQrYlrsxipJRLPdwnr1sHBRqSLowOD2q3dIL5KG" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/2.9.0/css/flag-icon.min.css"
        integrity="sha256-D+ZpDJjhGxa5ffyQkuTvwii4AntFGBZa4jUhSpdlhjM=" crossorigin="anonymous"/>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
{% include 'navbar.html' %}

<div class="container-fluid">
  {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{ message }}
    </div>
  {% endfor %}

  {% block content %}{% endblock %}
</div>

<footer class="text-center">
    <a class="text-light" href="https://github.com/kosior" target="_blank">
        <i class="fa fa-github fa-lg" aria-hidden="true"></i>
    </a>
</footer>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

{% block js %}{% endblock %}
</body>
</html>

ufcroster/templates/index.html
{% extends 'base.html' %}

{% block content %}
  <div class="container-fluid">
    <div class="alert alert-danger">
      Site is currently under development.
    </div>

    <div class="row justify-content-center mb-4">
      <div class="col-lg-6">
        <div class="card ur-shadow">
          <div id="subscribeContent" class="card-body text-center">
            <form id="subscriptionForm" action="{% url 'subscriptions:subscribe' %}" method="POST" class="form-inline justify-content-center">
              {% csrf_token %}
              <div class="form-group mr-2">
                <input type="email" class="form-control" name="email" placeholder="Enter email">
              </div>
              <button type="submit" class="btn btn-primary">Subscribe</button>
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="row justify-content-center">
      <div class="col-lg-3 col-12 text-center px-5">
        <h6 class="font-weight-bold">Closest fights</h6>
        <hr>
        {% for fight in closest_fights %}
          {% include 'fighters/snippets/fight_card.html' with fight=fight %}
        {% endfor%}
      </div>
      <div class="col-lg-3 col-12 text-center px-5">
        <h6 class="font-weight-bold">Recently added fights</h6>
        <hr>
        {% for fight in recently_added_fights %}
          {% include 'fighters/snippets/fight_card.html' with fight=fight %}
        {% endfor%}
      </div>
      <div class="col-lg-3 col-12 text-center px-5">
        <h6 class="font-weight-bold">Recently added fighters</h6>
        <hr>
        {% for fighter in recently_created_fighters %}
          {% include 'fighters/snippets/fighter_index_card.html' with fighter=fighter %}
        {% endfor%}
      </div>
    </div>
  </div>
{% endblock content %}

{% block js %}
  <script>
    var form = $('#subscriptionForm');
    form.submit(function (event) {
      event.preventDefault();
      $.post(form.attr('action'), form.serialize(), function (data) {
        $('#subscribeContent').html(data.msg);
      });
    });
  </script>
{% endblock js %}

ufcroster/templates/navbar.html
{% load active_countries %}

{% get_active_countries as countries %}

<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-primary px-5">
  <a class="navbar-brand" href="{% url 'fighters:index' %}">
    <div class='octagonWrap'>
      <div class='octagon text-center'></div>
      <div class="centerIcon"><i class="fa fa-globe logo-icon" aria-hidden="true"></i></div>
    </div>
    <div class="ml-1 brand-text">UFC Roster</div>
    <div class="flag-logo flag-icon flag-icon-{{ view.kwargs.country_code }}"></div>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarH"
          aria-controls="navbarH" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarH">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'fighters:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false">
          Countries
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% for country in countries %}
            <div class="p-2 d-flex align-items-center">
              <span class="flag-icon flag-icon-{{ country|lower }} mx-2 flag-menu"></span>
              <span class="mr-auto text-nowrap">{{ country.name }}</span>
              <a href="{% url 'fighters:by_country' country|lower %}" class="btn btn-sm btn-primary mx-2">Fighters</a>
              <a href="{% url 'fighters:upcoming_by_country' country|lower %}"
                 class="btn btn-sm btn-primary float-right">Upcoming fights</a>
            </div>
          {% endfor %}
        </div>
      </li>
    </ul>
  </div>
</nav>