config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


api_patterns = [
    url(r'^', include('fighters.api.urls')),
    url(r'^', include('events.api.urls')),
]


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(api_patterns, namespace='api')),
    url(r'subscription/', include('subscriptions.urls')),
    url(r'', include('fighters.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns

ufcroster/events/api/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'events', views.EventViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
]

ufcroster/fighters/urls.py
from django.conf.urls import url

from . import views

app_name = 'fighters'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<country_code>[\w]{2})/$', views.UpcomingFightsByCountry.as_view(), name='upcoming_by_country'),
    url(r'^(?P<country_code>[\w]{2})/fighters$', views.FightersByCountry.as_view(), name='by_country'),
    url(r'^fighter/(?P<slug>[\w\-]+)/$', views.FighterDetail.as_view(), name='detail'),
]

ufcroster/subscriptions/urls.py
from django.conf.urls import url

from . import views

app_name = 'subscriptions'


urlpatterns = [
    url(r'^$', views.Subscribe.as_view(), name='subscribe'),
    url(r'^activate$', views.ActivateSubscription.as_view(), name='activate'),
    url(r'^deactivate$', views.DeactivateSubscription.as_view(), name='deactivate'),
]

ufcroster/common/models.py
from django.db import models


class TimeStampedModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

ufcroster/events/models.py
from django.db import models

from common.models import TimeStampedModel


class Event(TimeStampedModel):
    title = models.CharField(max_length=255)
    date = models.DateTimeField(blank=True, null=True)
    location = models.CharField(max_length=255, blank=True)
    venue = models.CharField(max_length=255, blank=True)
    poster = models.ImageField(blank=True)
    promotion = models.CharField(max_length=255, blank=True)
    sherdog_url = models.URLField(max_length=255, blank=True, null=True)
    ufc_url = models.URLField(max_length=255, blank=True, null=True)
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.title

ufcroster/subscriptions/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from model_utils.models import TimeStampedModel

from .managers import NotificationManager, SubscriptionsManager


class Notification(TimeStampedModel):
    UPCOMING = 'U'
    RESULTS = 'R'

    TYPES = (
        (UPCOMING, 'Upcoming'),
        (RESULTS, 'Results')
    )

    type = models.CharField(max_length=4, choices=TYPES)
    response_id = models.CharField(max_length=128, blank=True, null=True)

    objects = NotificationManager()


class Subscription(TimeStampedModel):
    email = models.EmailField(unique=True)
    token = models.CharField(max_length=256, unique=True)
    is_active = models.BooleanField(default=False)

    objects = SubscriptionsManager()

    def __str__(self):
        return f'{self.email} Active: {self.is_active}'

    @property
    def action_link(self):
        if self.token:
            if not self.is_active:
                part_url = reverse('subscriptions:activate')
                return f'{settings.SITE_URL}{part_url}?token={self.token}'
            else:
                part_url = reverse('subscriptions:deactivate')
                return f'{settings.SITE_URL}{part_url}?token={self.token}'

    @property
    def unsubscribe_dict(self):
        return {'unsubscribe': self.action_link}

ufcroster/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

ufcroster/subscriptions/forms.py
from django.forms import ModelForm, ValidationError

from .models import Subscription


class SubscriptionForm(ModelForm):
    class Meta:
        model = Subscription
        fields = ('email', )

    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            subscription = Subscription.objects.get(email=email)
        except Subscription.DoesNotExist:
            return email
        else:
            if subscription.is_active:
                raise ValidationError('You have already subscribed.')
            if not subscription.is_active and subscription.token:
                raise ValidationError('Activation link already sent.')
            raise ValidationError('Please contact admin@ufcroster.com')

ufcroster/events/api/views.py
from rest_framework import viewsets

from .serializers import EventSerializer
from ..models import Event


class EventViewSet(viewsets.ModelViewSet):
    queryset = Event.objects.all()
    serializer_class = EventSerializer
    lookup_field = 'id'

ufcroster/fighters/api/views.py
from django.shortcuts import get_object_or_404
from rest_framework import viewsets

from .serializers import FighterSerializer, FightSerializer
from ..models import Fighter, Fight


class FighterViewSet(viewsets.ModelViewSet):
    queryset = Fighter.objects.details()
    serializer_class = FighterSerializer
    lookup_field = 'slug'


class FightViewSet(viewsets.ModelViewSet):
    serializer_class = FightSerializer

    def get_serializer(self, *args, **kwargs):
        if 'data' in kwargs:
            data = kwargs['data']
            if isinstance(data, list):
                kwargs['many'] = True

        return super().get_serializer(*args, **kwargs)

    def get_queryset(self):
        slug = self.kwargs.get('slug')
        fighter = get_object_or_404(Fighter, slug=slug)
        return Fight.objects.full_fights(fighter=fighter)

ufcroster/fighters/views.py
from django.conf import settings
from django.http import Http404
from django.views.generic import DetailView, ListView, TemplateView

from .models import Fighter, Fight


class CountryCodeMixin:
    def get_country_code(self):
        country_code = self.kwargs.get('country_code', '').upper()
        if country_code in settings.COUNTRIES_URL_CODES:
            return country_code
        raise Http404


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        fights_qs = Fight.objects.upcoming().fight_with_relations()
        context['closest_fights'] = fights_qs.order_by('details__date')[:5]
        context['recently_added_fights'] = fights_qs.order_by('-created')[:5]
        context['recently_created_fighters'] = Fighter.objects.details().active().order_by('-created')[:5]
        return context


class FighterDetail(DetailView):
    model = Fighter
    queryset = Fighter.objects.details()
    context_object_name = 'fighter'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['fights_list'] = Fight.objects.fight_with_relations().filter(fighter=self.object)
        return context


class UpcomingFightsByCountry(CountryCodeMixin, ListView):
    context_object_name = 'fights'
    template_name = 'fighters/upcoming_by_country.html'

    def get_queryset(self):
        return Fight.objects.upcoming_by_country(self.get_country_code()).order_by('details__date')


class FightersByCountry(CountryCodeMixin, ListView):
    context_object_name = 'fighters'
    template_name = 'fighters/fighters.html'

    def get_queryset(self):
        in_ufc = 'released_retired' not in self.request.GET.keys()
        return Fighter.objects.by_country(self.get_country_code()).filter(in_ufc=in_ufc)

ufcroster/subscriptions/views.py
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import redirect
from django.views.generic import View
from django.views.generic.edit import BaseCreateView

from .forms import SubscriptionForm
from .models import Subscription
from .utils import generate_token


class Subscribe(BaseCreateView):
    model = Subscription
    form_class = SubscriptionForm
    http_method_names = ['post']

    def form_invalid(self, form):
        return JsonResponse({'msg': form.errors.get('email', 'Something went wrong.')})

    def form_valid(self, form):
        form.save()
        return JsonResponse({'msg': 'Thank you for subscribing. Email has been sent to you with activation link.'})


class ActivateSubscription(View):
    def get(self, request, *args, **kwargs):
        token = request.GET.get('token')
        if token:
            try:
                subscription = Subscription.objects.get(token=token, is_active=False)
            except Subscription.DoesNotExist:
                messages.error(request, 'Activation link is no longer valid.')
            else:
                subscription.is_active = True
                subscription.token = generate_token(subscription.email, True)  # generating deactivation token
                subscription.save()
                messages.success(request, 'Subscription has been activated.')
        else:
            messages.error(request, 'Token not provided.')

        return redirect('fighters:index')


class DeactivateSubscription(View):
    def get(self, request, *args, **kwargs):
        token = request.GET.get('token')
        if token:
            try:
                subscription = Subscription.objects.get(token=token, is_active=True)
            except Subscription.DoesNotExist:
                messages.error(request, 'Deactivation link is no longer valid.')
            else:
                subscription.delete()
                messages.success(request, 'Subscription has been deactivated.')
        else:
            messages.error(request, 'Token not provided.')

        return redirect('fighters:index')

ufcroster/templates/fighters/snippets/fight_card.html
<div class="card mb-3 ur-shadow ur-bt" style="min-height: 120px;">
  <div class="card-header p-0 font-weight-bold text-left pl-3 border-0 card-bg">
    {% include 'fighters/snippets/fighter_anchor.html' with fighter=fight.fighter %}
  </div>
  <div class="card-body p-0 d-flex">
    <div class="row align-self-center">
      <div class="col-3 align-self-center pr-0">
        <img src="{{ fight.fighter.image.url }}" class="img-fluid">
      </div>
      <div class="col-6 align-self-center p-0" style="font-size: 12px; opacity: 0.8;">
        <div>{{ fight.details.date }}</div>
        <div></div>
        <div>{{ fight.details.event }}</div>
      </div>
      <div class="col-3 align-self-center pl-0">
        <img src="{{ fight.opponent.image.url }}" class="img-fluid">
      </div>
    </div>
  </div>
  <div class="card-footer p-0 font-weight-bold text-right pr-3 border-0 card-bg">
    {% include 'fighters/snippets/fighter_anchor.html' with fighter=fight.opponent %}
  </div>
</div>

ufcroster/templates/fighters/snippets/fighter_anchor.html
{% if fighter.active %}
  <a class="text-primary" href="{% url 'fighters:detail' fighter.slug %}">{{ fighter.name }}</a>
{% else %}
  <a class="text-primary" href="{{ fighter.urls.sherdog }}" target="_blank">
    {{ fighter.name }} <i class="fa fa-external-link-square" aria-hidden="true"></i>
  </a>
{% endif %}

ufcroster/templates/fighters/snippets/fighter_bio_left.html
{% load staticfiles %}

<div class="card ur-shadow">
    <div class="card-header text-center">
        <h3>{{ fighter.name }}</h3>
        <div>{{ fighter.record.total }}</div>
    </div>

    <div class="text-center">
        <img class="card-img rounded-0 img-fluid" style="max-width: 250px;"
             src="{{ fighter.image.url }}" alt="fighter">
    </div>

    <div class="card-body px-1">
        <div class="row">
            {% if fighter.nickname %}
                <div class="col-lg-5 col-md-3 col-6 text-right">Nickname:</div>
                <div class="col-lg-7 col-md-3 col-6 text-left font-weight-bold">{{ fighter.nickname }}</div>
            {% endif %}

            <div class="col-lg-5 col-md-3 col-6 text-right">Brithdate:</div>
            <div class="col-lg-7 col-md-3 col-6 text-left font-weight-bold">{{ fighter.birthdate }}</div>

            <div class="col-lg-5 col-md-3 col-6 text-right">Brithplace:</div>
            <div class="col-lg-7 col-md-3 col-6 text-left font-weight-bold">{{ fighter.birthplace }}</div>

            <div class="col-lg-5 col-md-3 col-6 text-right">Country:</div>
            <div class="col-lg-7 col-md-3 col-6 text-left font-weight-bold">{{ fighter.country.name }} <i class="{{ fighter.country.flag_css }}"></i></div>

            <div class="col-lg-5 col-md-3 col-6 text-right">Height:</div>
            <div class="col-lg-7 col-md-3 col-6 text-left font-weight-bold">{{ fighter.height }} cm ({{ fighter.height_imp }})</div>

            <div class="col-lg-5 col-md-3 col-6 text-right">Weight:</div>
            <div class="col-lg-7 col-md-3 col-6 text-left font-weight-bold">{{ fighter.weight }} kg ({{ fighter.weight_imp }})</div>

            <div class="col-lg-5 col-md-3 col-6 text-right">Weight class:</div>
            <div class="col-lg-7 col-md-3 col-6 text-left font-weight-bold">{{ fighter.weight_class }}</div>

            <div class="col-lg-5 col-md-3 col-6 text-right">Reach:</div>
            <div class="col-lg-7 col-md-3 col-6 text-left font-weight-bold">{{ fighter.reach }}</div>

            <div class="col-lg-5 col-md-3 col-6 text-right">Team:</div>
            <div class="col-lg-7 col-md-3 col-6 text-left font-weight-bold">{{ fighter.team }}</div>
        </div>
    </div>
</div>

ufcroster/templates/fighters/snippets/fighter_card.html
{% load staticfiles %}

<div class="m-2">
    <a class="btn text-primary font-weight-bold" href="{% url 'fighters:detail' fighter.slug %}">
        <div class="card text-center h-100 border-0 ur-shadow" style="width: 11rem;">
            <div class="card-header word-wrap p-1 border-0">{{ fighter.name }}</div>
            <img class="card-img rounded-0" src="{{ fighter.image.url }}" alt="">
            <div class="card-footer"><p class="card-text">{{ fighter.record.total }}</p></div>
        </div>
    </a>
</div>

ufcroster/templates/fighters/snippets/fighter_fights.html
{% load fighter_tags %}

{% for fight in fights_list %}
  {% if fight.details.status == 'U' %}
    {% include 'fighters/snippets/fighter_upcoming.html' with upcoming_fight=fight %}
  {% else %}
    {% ifchanged fight.details.type %}
      <div class="card my-3 px-3 ur-shadow">
        <div class="card-header p-0">
          <div class="text-center font-weight-bold h3 m-0">{{ fight.details.get_type_display }} Fights</div>
        </div>
        <div class="container-fluid d-none d-lg-block">
          <div class="row">
            <div class="col-lg-1 text-center p-0">Date</div>
            <div class="col-lg-1 text-center p-0">Result</div>
            <div class="col-lg-2 text-center p-0">Opponent</div>
            <div class="col-lg-2 text-center p-0">Opponent last 5<br>
              <small class="">latest to oldest</small>
            </div>
            <div class="col-lg-2 text-center p-0">Opponent record before</div>
            <div class="col-lg-2 text-center p-0">Method</div>
            <div class="col-lg-1 text-center p-0">Round</div>
            <div class="col-lg-1 text-center p-0">Time</div>
          </div>
        </div>
      </div>

    {% endifchanged %}

    <div class="card border-{% result_badge fight.result %} mb-2 mx-3 ur-shadow" style="font-size: 13px; border-width: 3px;">
      <div class="container-fluid">
        <div class="row">
          <div class="col-3 d-lg-none text-right p-0">Date:</div>
          <div class="col-lg-1 col-9 text-center p-0 align-self-center">
            {{ fight.details.date|date:'SHORT_DATE_FORMAT' }}
          </div>

          <div class="col-3 d-lg-none text-right p-0">Result:</div>
          <div class="col-lg-1 col-9 text-center p-0 align-self-center">
            <h6 class="m-0">
              <span class="badge badge-pill badge-{% result_badge fight.result %}">
                {{ fight.get_result_display }}
              </span>
            </h6>
          </div>

          <div class="col-3 d-lg-none text-right p-0">Opponent:</div>
          <div class="col-lg-2 col-9 text-center p-0 align-self-center font-weight-bold">
            {% include 'fighters/snippets/fighter_anchor.html' with fighter=fight.opponent %}
          </div>

          <div class="col-3 d-lg-none text-right p-0">Opponent last 5:</div>
          <div class="col-lg-2 col-9 text-center p-0 align-self-center">
            {% include 'fighters/snippets/fighter_last_5.html' with last_5_results=fight.opponent_last_5_list %}
          </div>

          <div class="col-3 d-lg-none text-right p-0">Opponent record before:</div>
          <div class="col-lg-2 col-9 text-center p-0 align-self-center">
            {{ fight.opponent_record_before|default:'-' }}
          </div>

          <div class="col-3 d-lg-none text-right p-0">Method:</div>
          <div class="col-lg-2 col-9 text-center p-0 align-self-center">
            {{ fight.details.method_display|linebreaksbr }}
          </div>

          <div class="col-3 d-lg-none text-right p-0">Round:</div>
          <div class="col-lg-1 col-9 text-center p-0 align-self-center">{{ fight.details.round }}</div>

          <div class="col-3 d-lg-none text-right p-0">Time:</div>
          <div class="col-lg-1 col-9 text-center p-0 align-self-center">{{ fight.details.time }}</div>
        </div>
      </div>

      <div class="card-footer text-center p-0">{{ fight.details.event.title }}</div>
    </div>
  {% endif %}
{% endfor %}

ufcroster/templates/fighters/snippets/fighter_index_card.html
<div class="card mb-3 ur-shadow ur-bt" style="min-height: 120px;">
  <div class="card-body p-2">
      <div class="row">
        <div class="col-4 pr-0">
          <img src="{{ fighter.image.url }}" class="img-fluid">
        </div>
        <div class="col-8 text-left">
          <div>
            <a class="text-primary font-weight-bold" href="{% url 'fighters:detail' fighter.slug %}">
              {{ fighter.name }}
            </a>
          </div>
          <div>{{ fighter.record.total }}</div>
          <div>{{ fighter.weight_class }}</div>
          <div><i class="flag-icon flag-icon-{{ fighter.country.code|lower }}"></i> {{ fighter.country.name }}</div>
        </div>
      </div>
  </div>
</div>

ufcroster/templates/fighters/snippets/fighter_last_5.html
{% load fighter_tags %}

{% for result in last_5_results %}
  <div class="badge text-center bg-{% result_badge result %}" style="width: 25px; margin: 1px">{{ result }}</div>
{% empty %}
  <div class="badge text-center">-</div>
{% endfor %}
{% if show_description %}
  <small><br>last 5 fights (latest to oldest)</small>
{% endif %}

ufcroster/templates/fighters/snippets/fighter_record.html
<div class="row p-1 pb-3">
    <div class="col-sm d-flex flex-column">
        <div class="text-center text-success pb-1"><strong>WINS</strong></div>
        <div class="row align-items-lg-center border-top border-success m-0 h-100 ur-border-w">
            <div class="col-lg-6 col-md-12 text-center" style="font-size: 40px;">{{ fighter.record.wins }}</div>
            <div class="col-lg-6 col-md-12 text-lg-left text-center pr-0 pl-2" style="font-size: 11px;">
                <div>{{ fighter.record.wins_ko_tko }} - KO/TKO</div>
                <div>{{ fighter.record.wins_sub }} - SUBMISSIO{{ fighter.record.wins_sub|pluralize:"N,NS" }}</div>
                <div>{{ fighter.record.wins_dec }} - DECISIO{{ fighter.record.wins_dec|pluralize:"N,NS" }}</div>
                {% if fighter.record.wins_other %}
                    <div>{{ fighter.record.wins_other }} - OTHE{{ fighter.record.wins_other|pluralize:"R,RS" }}</div>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-sm d-flex flex-column">
        <div class="text-center text-danger pb-1"><strong>LOSSES</strong></div>
        <div class="row align-items-lg-center border-top border-danger m-0 h-100 ur-border-w">
            <div class="col-lg-6 col-md-12 text-center" style="font-size: 40px;">{{ fighter.record.losses }}</div>
            <div class="col-lg-6 col-md-12 text-lg-left text-center pr-0 pl-2" style="font-size: 11px;">
                <div>{{ fighter.record.losses_ko_tko }} - KO/TKO</div>
                <div>{{ fighter.record.losses_sub }} - SUBMISSIO{{ fighter.record.losses_sub|pluralize:"S,NS" }}</div>
                <div>{{ fighter.record.losses_dec }} - DECISIO{{ fighter.record.losses_dec|pluralize:"N,NS" }}</div>
                {% if fighter.record.losses_other %}
                    <div>{{ fighter.record.losses_other }} - OTHE{{ fighter.record.losses_other|pluralize:"R,RS" }}</div>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-sm d-flex flex-column">
        <div class="text-center text-info pb-1"><strong>DRAWS</strong></div>
        <div class="row align-items-lg-center border-top border-info m-0 h-100 ur-border-w">
            <div class="col-lg-12 col-md-12 text-center" style="font-size: 40px;">{{ fighter.record.draws }}</div>
        </div>
    </div>
    {% if fighter.record.nc %}
        <div class="col-sm d-flex flex-column">
            <div class="text-center text-light pb-1"><strong>N/C</strong></div>
            <div class="row align-items-lg-center border-top border-light m-0 h-100 ur-border-w">
                <div class="col-lg-6 col-md-12 text-center" style="font-size: 40px;">{{ fighter.record.nc }}</div>
            </div>
        </div>
    {% endif %}
</div>

ufcroster/templates/fighters/snippets/fighter_upcoming.html
<div class="card text-center mt-2 ur-shadow">
  <div class="card-header">
    {{ upcoming_fight.details.date }}
  </div>
  <div class="card-body">
    <div class="row text-center">
      <div class="col-lg-5">
        <div class="h2 font-weight-bold">{{ upcoming_fight.fighter }}</div>
        <div class="col text-center p-1 align-self-center">
          {% include 'fighters/snippets/fighter_last_5.html' with last_5_results=upcoming_fight.fighter.record.last_5_list show_description=True %}
        </div>
        <br>
        {{ upcoming_fight.fighter.record.total }}
      </div>
      <div class="col-lg-2 h2">vs.</div>
      <div class="col-lg-5">
        <div class="h2 font-weight-bold">
          {% include 'fighters/snippets/fighter_anchor.html' with fighter=upcoming_fight.opponent %}
        </div>
        <div class="col text-center p-1 align-self-center">
          {% include 'fighters/snippets/fighter_last_5.html' with last_5_results=upcoming_fight.opponent_last_5_list show_description=True %}
        </div>
        <br>
        {{ upcoming_fight.opponent_record_before|default:'-' }}
      </div>
    </div>
  </div>
  <div class="card-footer">
    {{ upcoming_fight.details.event.title }}
  </div>
</div>

ufcroster/templates/fighters/snippets/fighter_urls.html
<div class="container my-0">
    <div class="row justify-content-lg-center">
        {% for url_, display in fighter.urls.display_list %}
            <div class="col-lg-1 col-md-3 col-sm-6 col-6 mb-2 text-center">
                <a class="btn btn-outline-primary btn-sm btn-block btn-f-url" href="{{ url_ }}" target="_blank">
                    {{ display|safe }}
                </a>
            </div>
        {% endfor %}
    </div>
</div>