config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


api_patterns = [
    url(r'^', include('fighters.api.urls')),
    url(r'^', include('events.api.urls')),
]


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(api_patterns, namespace='api')),
    url(r'subscription/', include('subscriptions.urls')),
    url(r'', include('fighters.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns

ufcroster/events/api/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'events', views.EventViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
]

ufcroster/fighters/urls.py
from django.conf.urls import url

from . import views

app_name = 'fighters'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<country_code>[\w]{2})/$', views.UpcomingFightsByCountry.as_view(), name='upcoming_by_country'),
    url(r'^(?P<country_code>[\w]{2})/fighters$', views.FightersByCountry.as_view(), name='by_country'),
    url(r'^fighter/(?P<slug>[\w\-]+)/$', views.FighterDetail.as_view(), name='detail'),
]

ufcroster/subscriptions/urls.py
from django.conf.urls import url

from . import views

app_name = 'subscriptions'


urlpatterns = [
    url(r'^$', views.Subscribe.as_view(), name='subscribe'),
    url(r'^activate$', views.ActivateSubscription.as_view(), name='activate'),
    url(r'^deactivate$', views.DeactivateSubscription.as_view(), name='deactivate'),
]

ufcroster/common/models.py
from django.db import models


class TimeStampedModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

ufcroster/events/models.py
from django.db import models

from common.models import TimeStampedModel


class Event(TimeStampedModel):
    title = models.CharField(max_length=255)
    date = models.DateTimeField(blank=True, null=True)
    location = models.CharField(max_length=255, blank=True)
    venue = models.CharField(max_length=255, blank=True)
    poster = models.ImageField(blank=True)
    promotion = models.CharField(max_length=255, blank=True)
    sherdog_url = models.URLField(max_length=255, blank=True, null=True)
    ufc_url = models.URLField(max_length=255, blank=True, null=True)
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.title

ufcroster/subscriptions/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from model_utils.models import TimeStampedModel

from .managers import NotificationManager, SubscriptionsManager


class Notification(TimeStampedModel):
    UPCOMING = 'U'
    RESULTS = 'R'

    TYPES = (
        (UPCOMING, 'Upcoming'),
        (RESULTS, 'Results')
    )

    type = models.CharField(max_length=4, choices=TYPES)
    response_id = models.CharField(max_length=128, blank=True, null=True)

    objects = NotificationManager()


class Subscription(TimeStampedModel):
    email = models.EmailField(unique=True)
    token = models.CharField(max_length=256, unique=True)
    is_active = models.BooleanField(default=False)

    objects = SubscriptionsManager()

    def __str__(self):
        return f'{self.email} Active: {self.is_active}'

    @property
    def action_link(self):
        if self.token:
            if not self.is_active:
                part_url = reverse('subscriptions:activate')
                return f'{settings.SITE_URL}{part_url}?token={self.token}'
            else:
                part_url = reverse('subscriptions:deactivate')
                return f'{settings.SITE_URL}{part_url}?token={self.token}'

    @property
    def unsubscribe_dict(self):
        return {'unsubscribe': self.action_link}

ufcroster/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

ufcroster/subscriptions/forms.py
from django.forms import ModelForm, ValidationError

from .models import Subscription


class SubscriptionForm(ModelForm):
    class Meta:
        model = Subscription
        fields = ('email', )

    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            subscription = Subscription.objects.get(email=email)
        except Subscription.DoesNotExist:
            return email
        else:
            if subscription.is_active:
                raise ValidationError('You have already subscribed.')
            if not subscription.is_active and subscription.token:
                raise ValidationError('Activation link already sent.')
            raise ValidationError('Please contact admin@ufcroster.com')

ufcroster/events/api/views.py
from rest_framework import viewsets

from .serializers import EventSerializer
from ..models import Event


class EventViewSet(viewsets.ModelViewSet):
    queryset = Event.objects.all()
    serializer_class = EventSerializer
    lookup_field = 'id'

ufcroster/fighters/api/views.py
from django.shortcuts import get_object_or_404
from rest_framework import viewsets

from .serializers import FighterSerializer, FightSerializer
from ..models import Fighter, Fight


class FighterViewSet(viewsets.ModelViewSet):
    queryset = Fighter.objects.details()
    serializer_class = FighterSerializer
    lookup_field = 'slug'


class FightViewSet(viewsets.ModelViewSet):
    serializer_class = FightSerializer

    def get_serializer(self, *args, **kwargs):
        if 'data' in kwargs:
            data = kwargs['data']
            if isinstance(data, list):
                kwargs['many'] = True

        return super().get_serializer(*args, **kwargs)

    def get_queryset(self):
        slug = self.kwargs.get('slug')
        fighter = get_object_or_404(Fighter, slug=slug)
        return Fight.objects.full_fights(fighter=fighter)

ufcroster/fighters/views.py
from django.conf import settings
from django.http import Http404
from django.views.generic import DetailView, ListView, TemplateView

from .models import Fighter, Fight


class CountryCodeMixin:
    def get_country_code(self):
        country_code = self.kwargs.get('country_code', '').upper()
        if country_code in settings.COUNTRIES_URL_CODES:
            return country_code
        raise Http404


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        fights_qs = Fight.objects.upcoming().fight_with_relations()
        context['closest_fights'] = fights_qs.order_by('details__date')[:5]
        context['recently_added_fights'] = fights_qs.order_by('-created')[:5]
        context['recently_created_fighters'] = Fighter.objects.details().active().order_by('-created')[:5]
        return context


class FighterDetail(DetailView):
    model = Fighter
    queryset = Fighter.objects.details()
    context_object_name = 'fighter'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['fights_list'] = Fight.objects.fight_with_relations().filter(fighter=self.object)
        return context


class UpcomingFightsByCountry(CountryCodeMixin, ListView):
    context_object_name = 'fights'
    template_name = 'fighters/upcoming_by_country.html'

    def get_queryset(self):
        return Fight.objects.upcoming_by_country(self.get_country_code()).order_by('details__date')


class FightersByCountry(CountryCodeMixin, ListView):
    context_object_name = 'fighters'
    template_name = 'fighters/fighters.html'

    def get_queryset(self):
        in_ufc = 'released_retired' not in self.request.GET.keys()
        return Fighter.objects.by_country(self.get_country_code()).filter(in_ufc=in_ufc)

ufcroster/subscriptions/views.py
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import redirect
from django.views.generic import View
from django.views.generic.edit import BaseCreateView

from .forms import SubscriptionForm
from .models import Subscription
from .utils import generate_token


class Subscribe(BaseCreateView):
    model = Subscription
    form_class = SubscriptionForm
    http_method_names = ['post']

    def form_invalid(self, form):
        return JsonResponse({'msg': form.errors.get('email', 'Something went wrong.')})

    def form_valid(self, form):
        form.save()
        return JsonResponse({'msg': 'Thank you for subscribing. Email has been sent to you with activation link.'})


class ActivateSubscription(View):
    def get(self, request, *args, **kwargs):
        token = request.GET.get('token')
        if token:
            try:
                subscription = Subscription.objects.get(token=token, is_active=False)
            except Subscription.DoesNotExist:
                messages.error(request, 'Activation link is no longer valid.')
            else:
                subscription.is_active = True
                subscription.token = generate_token(subscription.email, True)  # generating deactivation token
                subscription.save()
                messages.success(request, 'Subscription has been activated.')
        else:
            messages.error(request, 'Token not provided.')

        return redirect('fighters:index')


class DeactivateSubscription(View):
    def get(self, request, *args, **kwargs):
        token = request.GET.get('token')
        if token:
            try:
                subscription = Subscription.objects.get(token=token, is_active=True)
            except Subscription.DoesNotExist:
                messages.error(request, 'Deactivation link is no longer valid.')
            else:
                subscription.delete()
                messages.success(request, 'Subscription has been deactivated.')
        else:
            messages.error(request, 'Token not provided.')

        return redirect('fighters:index')

ufcroster/templates/fighters/fighter_detail.html
{% extends 'base.html' %}

{% load staticfiles %}

{% load cache %}

{% block title %}
    {{ fighter.name }}
{% endblock %}

{% block content %}

    {% include 'fighters/snippets/fighter_urls.html' %}
    <div class="container-fluid my-1">
        <div class="row">
            <div class="col-lg-3 col-md-12">
                {% include 'fighters/snippets/fighter_bio_left.html' %}
            </div>
            <div class="col-lg-9 col-md-12">
                <div class="card ur-shadow">
                    {% include 'fighters/snippets/fighter_record.html' %}
                </div>
                {% cache 86400 fights fighter.id %}
                  {% include 'fighters/snippets/fighter_fights.html' %}
                {% endcache %}
            </div>
        </div>
    </div>
{% endblock %}

ufcroster/templates/fighters/fighters.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}
  Fighters
{% endblock %}

{% block content %}
  <div class="container-fluid my-1">
    <div class="row">
      <div class="col">
        {% if request.GET.released_retired is None %}
          <a href="{% url 'fighters:by_country' view.kwargs.country_code %}?released_retired" class="btn btn-primary pull-right">Released or retired</a>
        {% else %}
          <a href="{% url 'fighters:by_country' view.kwargs.country_code %}" class="btn btn-primary pull-right">Currently in UFC</a>
        {% endif %}
      </div>
    </div>

    <div class="d-flex justify-content-center flex-wrap">
      {% for fighter in fighters %}
        {% include 'fighters/snippets/fighter_card.html' with fighter=fighter %}
      {% empty %}
        Fighters not found.
      {% endfor %}
    </div>
  </div>
{% endblock %}

ufcroster/templates/fighters/upcoming_by_country.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}
  Upcoming
{% endblock %}

{% block content %}
  <div class="container mt-2">
    {% for fight in fights %}
      <div class="card mb-3 ur-shadow">
        <div class="card-header p-0 text-center">{{ fight.details.date }}</div>
        <div class="card-body p-1">
          <div class="row">
            <div class="col-lg-12">
              <div class="row text-center">
                <div class="col-lg-2">
                  <a href="{% url 'fighters:detail' fight.fighter.slug %}">
                    <img style="height: 100px;" class="img-fluid rounded" src="{{ fight.fighter.image.url }}" alt="">
                  </a>
                </div>
                <div class="col-lg-3">
                  <div class="row">
                    <div class="col-lg-12 h5">
                      <a class="font-weight-bold text-primary" href="{% url 'fighters:detail' fight.fighter.slug %}">
                        {{ fight.fighter.name }}
                      </a>
                    </div>
                    <div class="col-lg-12 h6">{{ fight.fighter.record.total }}</div>
                    <div class="col-lg-12 h6">
                      {% include 'fighters/snippets/fighter_last_5.html' with last_5_results=fight.fighter.record.last_5_list show_description=True %}
                    </div>
                  </div>
                </div>
                <div class="col-lg-2 d-flex align-items-center justify-content-center">vs.</div>
                <div class="col-lg-3">
                  <div class="row">
                    <div class="col-lg-12 h5 font-weight-bold">
                      {% include 'fighters/snippets/fighter_anchor.html' with fighter=fight.opponent %}
                    </div>
                    <div class="col-lg-12 h6">{{ fight.opponent_record_before }}</div>
                    <div class="col-lg-12 h6">
                      {% include 'fighters/snippets/fighter_last_5.html' with last_5_results=fight.opponent_last_5_list show_description=True %}
                    </div>
                  </div>
                </div>
                <div class="col-lg-2">
                  <img style="height: 100px;" class="img-fluid rounded" src="{{ fight.opponent.image.url }}" alt="">
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="card-footer p-0 text-center">{{ fight.details.event }}</div>
      </div>
    {% endfor %}
  </div>
{% endblock %}